// Arquivo: minimalArgs.js
const minimalArgs = [
  "--disable-accelerated-2d-canvas",
  "--disable-application-cache",
  "--disable-client-side-phishing-detection",
  "--disable-component-update",
  "--disable-default-apps",
  "--disable-dev-shm-usage",
  "--disable-extensions",
  "--disable-gpu",
  "--disable-offer-store-unmasked-wallet-cards",
  "--disable-offline-load-stale-cache",
  "--disable-popup-blocking",
  "--disable-setuid-sandbox",
  "--disable-site-isolation-trials",
  "--disable-speech-api",
  "--disable-sync",
  "--disable-translate",
  "--disable-web-security",
  "--hide-scrollbars",
  "--ignore-certificate-errors",
  "--ignore-ssl-errors",
  "--metrics-recording-only",
  "--mute-audio",
  "--no-default-browser-check",
  "--no-first-run",
  "--no-pings",
  "--no-sandbox",
  "--no-zygote",
  "--password-store=basic",
  "--renderer-process-limit=2",
  "--safebrowsing-disable-auto-update",
  "--use-mock-keychain",
  "--window-size=1280,720",
  "--disk-cache-size=1073741824"
];

module.exports = minimalArgs;
